"""Add goals table with updated schema

Revision ID: f22e9dae9df9
Revises: bed2b9060df0
Create Date: 2025-10-28 23:03:45.532541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f22e9dae9df9'
down_revision: Union[str, Sequence[str], None] = 'bed2b9060df0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('goals', sa.Column('current_amount', sa.Float(), nullable=False))
    op.add_column('goals', sa.Column('monthly_contribution', sa.Float(), nullable=True))
    op.alter_column('goals', 'target_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.drop_column('goals', 'name')
    op.drop_column('goals', 'current_funding')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('current_funding', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('goals', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('goals', 'target_date',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('goals', 'monthly_contribution')
    op.drop_column('goals', 'current_amount')
    op.drop_column('goals', 'title')
    # ### end Alembic commands ###
