name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  # Update Python dependencies
  update-python-deps:
    name: Update Python Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Update dependencies
        working-directory: backend
        run: |
          uv sync --upgrade
          uv lock

      - name: Run tests
        working-directory: backend
        run: |
          uv run pytest tests/ -v

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore(deps): update Python dependencies'
          title: 'chore(deps): Update Python dependencies'
          body: |
            ## Python Dependency Updates

            This PR updates Python dependencies to their latest versions.

            ### Changes
            - Updated `pyproject.toml` and `uv.lock`
            - All tests passing

            ### Testing
            - ✅ Unit tests passed
            - ✅ Integration tests passed
          branch: deps/python-updates
          labels: dependencies,automated

  # Update npm dependencies
  update-npm-deps:
    name: Update npm Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Update dependencies
        working-directory: frontend
        run: |
          npm update
          npm audit fix --audit-level=moderate

      - name: Run tests
        working-directory: frontend
        run: |
          npm ci
          npm test -- --watchAll=false

      - name: Build
        working-directory: frontend
        run: npm run build

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore(deps): update npm dependencies'
          title: 'chore(deps): Update npm dependencies'
          body: |
            ## npm Dependency Updates

            This PR updates npm dependencies to their latest versions.

            ### Changes
            - Updated `package.json` and `package-lock.json`
            - All tests passing
            - Build successful

            ### Testing
            - ✅ Unit tests passed
            - ✅ Build succeeded
          branch: deps/npm-updates
          labels: dependencies,automated

  # Security vulnerability scanning
  security-scan:
    name: Security Vulnerability Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Snyk security scan
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

      - name: Run npm audit
        working-directory: frontend
        run: |
          npm audit --audit-level=high

      - name: Create security issue if vulnerabilities found
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🔒 Security vulnerabilities detected',
              body: 'Security scan found high severity vulnerabilities. Please review and update dependencies.',
              labels: ['security', 'high-priority']
            });
